export const LOADING = 'LOADING';
export const FETCH = 'FETCH';
export const FETCH_ENTITIES = 'FETCH_ENTITIES';
export const ERROR_FETCH_ENTITIES = 'ERROR_FETCH_ENTITIES';
export const LOADING_ENTITIES = 'LOADING_ENTITIES';
export const LOADING_COUNTRIES = 'LOADING_COUNTRIES';
export const FETCH_COUNTRIES = 'FETCH_COUNTRIES';
export const RETURN_TO_FIRST_STEP = 'RETURN_TO_FIRST_STEP';
export const PDF_LOADING = 'PDF_LOADING';
export const PDF_SUCCESS  = 'PDF_SUCCESS';
export const PDF_ERROR_POST  = 'PDF_ERROR_POST';
export const CONFIRM_PDF  = 'CONFIRM_PDF';
export const REJECT_PDF  = 'REJECT_PDF';
export const REJECT_PDF_LOADING  = 'REJECT_PDF_LOADING';
export const REJECT_PDF_ERROR  = 'REJECT_PDF_ERROR';
export const CONFIRM_PDF_LOADING = 'CONFIRM_PDF_LOADING';
export const NOTIFICATION_SENDED_SUCCESS  = 'NOTIFICATION_SENDED_SUCCESS';
export const INITIAL_STATE  = 'INITIAL_STATE';



