export const CREATE_USER_DEMAND = 'CREATE_USER_DEMAND';
export const GET_ENTITIES = 'GET_ENTITIES';
export const GET_PDF  = 'GET_PDF';
export const CONFIRM_PDF  = 'CONFIRM_PDF';
export const REJECT_PDF  = 'REJECT_PDF';
export const NOTIFICATION_SENDED_SUCCESS  = 'NOTIFICATION_SENDED_SUCCESS';



